name: Vprofile CICD WF
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '59 00 * * 1-5'  # Weekly on Sundays at midnight

env:
  ECR_REPOSITORY: 'github-actions'

permissions:
  contents: read
  #pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Maven build
        run: mvn install

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-artifacts
          path: target/*.war  

      - name: Build jobs failed
        if: failure()
        run: echo "Build job failed. Please check the logs."

  testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run tests on main branch
        if: github.ref == 'refs/heads/main'
        run: mvn test
      
      - name: Checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle

      - name: Run tests on other branches
        if: github.ref != 'refs/heads/main'
        run: echo "Skipping tests on non-main branches."
        
  security-scanning:
   runs-on: ubuntu-latest
   needs: build
   steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'json'
          output: 'trivy-report.json'
          exit-code: '0'
          ignore-unfixed: true

      - name: Upload Security Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

  BUILD_AND_PUBLISH:
    runs-on: ubuntu-latest
    needs: [build, testing, security-scanning]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPOSITORY:latest -t $ECR_REPOSITORY:$IMAGE_TAG -f Docker-files/app/multistage/Dockerfile .
          docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG